#!/bin/sh

set -eu

if [ -z "${HOME-}" ] || ! [ -w "${HOME}" ]; then
    export HOME="${AUTOPKGTEST_TMP}"
fi

export SDL_AUDIODRIVER=dummy
export SDL_VIDEODRIVER=dummy
export SDL2COMPAT_DEBUG_LOGGING=1

cd "$AUTOPKGTEST_TMP"

failed=0

/usr/libexec/installed-tests/SDL2/testtimer || failed=1

exit "$failed"
